# Generated by Django 5.2.6 on 2025-12-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
