# Generated by Django 5.2.6 on 2026-01-01 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_remove_image_author_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('family_status', models.CharField(blank=True, choices=[('Married', 'Женат/замужем'), ('Single', 'Холост'), ('Divorced', 'В разводе'), ('Widowed', 'Вдовец/Вдова'), ('Engaged', 'Помолвлен/помолвлена')], default='')),
                ('bio', models.CharField(blank=True, max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
