# Generated by Django 5.2.6 on 2026-01-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=512, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_status',
            field=models.CharField(blank=True, choices=[('Married', 'Женат/замужем'), ('Single', 'Холост'), ('Divorced', 'В разводе'), ('Widowed', 'Вдовец/Вдова'), ('Engaged', 'Помолвлен/помолвлена')], default='', verbose_name='Семейное положение'),
        ),
    ]
