# Generated by Django 5.2.6 on 2026-01-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_profile_age_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_status',
            field=models.CharField(blank=True, choices=[('Женат/замужем', 'Женат/замужем'), ('Не женат/Не замужем', 'Не женат/Не замужем'), ('В разводе', 'В разводе'), ('Вдовец/Вдова', 'Вдовец/Вдова'), ('Помолвлен/помолвлена', 'Помолвлен/помолвлена')], default='', verbose_name='Семейное положение'),
        ),
    ]
